spring:
  applicaation:
    name: msclientes
#  config:
#    import: configserver
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
server:
  port:0

eureka:
  client:
    service-url :
      defaaultZone: http://localhost:8761/eureka
    instance:
      instace-id : ${spring.application.name}:${spring.application.instance_id:${random.value}}
