spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 3000

eureka:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: lb://msclientes
          predicates: Path=/clientes/**
  client:
    registryWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
